variables:
  IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  # set via secret variables
  API_TOKEN: $PERSONAL_ACCESS_TOKEN
  PROJ_A_ID: $PROJ_A_ID
  PROJ_A_PIPELINE_TOKEN: $PROJ_A_PIPELINE_TOKEN
  PROJ_B_ID: $PROJ_B_ID
  PROJ_B_PIPELINE_TOKEN: $PROJ_B_PIPELINE_TOKEN
  REF: master


stages:
  - build
  - test
  - release


build-sha:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --pull -t $IMAGE .
    - docker push $IMAGE

test basic:
  stage: test
  image: $IMAGE
  script: 
    - trigger -a $API_TOKEN -r $REF $PROJ_B_ID


test legacy target flag:
  stage: test
  image: $IMAGE
  script:
    # parameter -t is deprecated
    - trigger -a $API_TOKEN -t $REF $PROJ_B_ID


test env variables:
  stage: test
  image: $IMAGE
  script: 
    - trigger -a $API_TOKEN -r $REF -e foo1=bar2 -e foo2=bar3 $PROJ_A_ID


test host & url:
  stage: test
  image: $IMAGE
  script: 
    - trigger -a $API_TOKEN -h gitlab.com -p $PROJ_B_PIPELINE_TOKEN -r $REF -u /api/v4/projects $PROJ_B_ID


test detach:
  stage: test
  image: $IMAGE
  script:
    - trigger -d -p $PROJ_A_PIPELINE_TOKEN -r $REF -e foo1=bar2 -e foo2=bar3 $PROJ_A_ID


.release_template: &release_template
  stage: release
  image: docker:latest
  services:
    - docker:dind


.image_release: &image_release
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $IMAGE
    - docker tag $IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE


release-latest:
  only:
    - master
  variables:
    RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  <<: *release_template
  <<: *image_release


release-tag:
  only:
    - tags
  variables:
    RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  <<: *release_template
  <<: *image_release
